### PR TITLE
Feature/initial code import

### PR DESCRIPTION
**Pull request by roscopeco**
* Just initial import of firmware / software + libs

### CODE REVIEW

**Comment by 0xTJ** [comment]
Are you intending to keep the original and Pro models having separate codebases (especially for the `software`) going forward?

**Comment by roscopeco** [comment]
> Are you intending to keep the original and Pro models having separate codebases (especially for the `software`) going forward?

I think so, yes. They're likely to diverge significantly enough that I think it's worth keeping them separate (though, at least for now, I'm keeping the layout the same so that you can build the old examples for the pro just by passing in the ROSCO_M68K_DIR as the pro directory).

**Review by 0xTJ — APPROVED** [review]
It's great to see that bring-up is going well!

The extra changes added in the non-huge commits make sense to me. :)

**Comment by roscopeco** [comment]
> It's great to see that bring-up is going well!
> 
> The extra changes added in the non-huge commits make sense to me. :)

Great, thanks for looking @0xTJ  :)

**Pull request merged**
